version: '3.8'

services:
  qron-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3090:3090'
    command: npm run start:dev
    volumes:
      - type: bind
        source: ./src/
        target: /app/src/
      - type: bind
        source: ./package.json
        target: /app/package.json
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgres://qron_usr:password@db:5432/qron-db
      API_KEY: qron_demo_BWyqXQoUFD3JyF9z5pY7UTPFzZH6dJey
    depends_on:
      - redis
    networks:
      - cron-network
    # env_file:
    #   - .env

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    networks:
      - cron-network

  db:
    image: postgres:17.2-alpine
    volumes:
      - qron_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'qron-db'
      POSTGRES_USER: qron_usr
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5430:5432'
    networks:
      - cron-network

networks:
  cron-network:
    driver: bridge

volumes:
  qron_data:
